version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      - REACT_APP_API_PORT=3001
      - REACT_APP_API_URL=api

  api:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - CORS_URL=frontend
      - CORS_PORT=3000
      - MONGO_PORT=27017
      - MONGO_URL=api_mongo
  api_mongo:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_api:
